# -*- coding: utf-8 -*-
"""10 月批次四：2026-10-14 ~ 10-17（16 篇）+ 当当 ep30/31/32（3 篇）。"""

RAW_OCT_4 = [
    # ================= 2026-10-14 =================
    {
        "dateStr": "2026-10-14", "kind": "regular", "language": "zh",
        "title": "小鸭子洗澡澡（0-1岁）",
        "preview": "浴盆里，小黄鸭游啊游。捏一捏，嘎——宝宝拍拍水，哗啦哗啦。洗个香香的澡，睡觉觉喽。",
        "moral": "洗澡不只是洗干净：玩水、听声、大笑，都是宝宝快乐的一天。",
        "content": [
            "浴盆里，水暖暖。",
            "小黄鸭，游啊游。",
            "宝宝捏一捏——嘎！",
            "小黄鸭唱歌啦。",
            "宝宝拍拍水，",
            "哗啦哗啦，",
            "溅起小水花。",
            "泡泡飞呀飞。",
            "洗个香香的澡，擦干干，暖乎乎——睡觉觉喽。晚安，小鸭子。"
        ],
    },
    {
        "dateStr": "2026-10-14", "kind": "regular", "language": "en",
        "title": "Splish Splash, Little Duck (0-1 yr)",
        "preview": "In the warm tub, the little yellow duck swims around. Squeeze it — quack! Baby pats the water, splish splash. A sweet bath, then off to bed.",
        "moral": "Bath time is more than getting clean: splashing, quacking, giggling — all the joy of baby's day.",
        "content": [
            "In the tub, warm warm water.",
            "Little yellow duck swims, swims.",
            "Baby squeezes — quack!",
            "The duck is singing!",
            "Baby pats the water,",
            "splish, splash, splish, splash,",
            "little drops jump up.",
            "Bubbles float, float, float.",
            "A sweet, sweet bath — dry off, warm up — bedtime! Good night, little duck."
        ],
    },
    {
        "dateStr": "2026-10-14", "kind": "science", "language": "zh",
        "title": "🔬科学故事（0-1岁）：小黄鸭为什么浮在水上",
        "preview": "小黄鸭放进浴盆，飘——稳稳地浮着。宝宝的小脚丫伸下去，却会沉一点。这是为什么？",
        "moral": "小黄鸭的肚子里藏着空气，像小船一样，比同体积的水轻，所以浮着；实物比水重的就会沉下去。",
        "content": [
            "小黄鸭，进浴盆。",
            "飘——浮着啦。",
            "摇一摇，晃一晃，",
            "就是不沉底。",
            "小黄鸭有秘密。",
            "它肚子里藏着空气。",
            "像一只小船，",
            "比同样大小的水轻。",
            "轻的浮起来，重的沉下去——所以小黄鸭稳稳漂着，帮宝宝洗澡澡。"
        ],
    },
    {
        "dateStr": "2026-10-14", "kind": "science", "language": "en",
        "title": "🔬 Science Story (0-1 yr): Why the Rubber Duck Floats",
        "preview": "The rubber duck goes into the tub — float! It stays up steadily. Why does it never sink?",
        "moral": "The duck hides air inside its belly, like a little boat lighter than the same amount of water — so it floats.",
        "content": [
            "The rubber duck goes in.",
            "Float! It stays up.",
            "Rock, rock, wobble, wobble,",
            "it never sinks.",
            "The duck has a secret.",
            "Air hides in its belly.",
            "Like a little, little boat,",
            "lighter than the water it pushes.",
            "Light things float, heavy things sink — so the duck floats steadily through bath time."
        ],
    },
    # ================= 2026-10-15 =================
    {
        "dateStr": "2026-10-15", "kind": "regular", "language": "zh",
        "title": "抱抱是最暖和的（0-1岁）",
        "preview": "被子暖，毯子暖，小袜子也暖。可是宝宝哭的时候，什么最管用？——抱抱。张开手臂，抱进怀里，慢慢就不哭啦。",
        "moral": "抱抱是世界上最暖和的东西：比被子暖，比毯子暖，因为爱是热的。",
        "content": [
            "被子暖暖的。",
            "毯子暖暖的。",
            "小袜子也暖暖的。",
            "宝宝哭了，呜呜。",
            "被子抱不动，",
            "毯子抱不动，",
            "小袜子也抱不动。",
            "妈妈张开手臂——抱抱。",
            "抱进怀里，轻轻拍。呜呜变小了，变成呼噜噜。抱抱最暖和，因为爱是热的。"
        ],
    },
    {
        "dateStr": "2026-10-15", "kind": "regular", "language": "en",
        "title": "A Hug Is Warmest (0-1 yr)",
        "preview": "The quilt is warm. The blanket is warm. The socks are warm too. But when baby cries, what works best? — A hug.",
        "moral": "A hug is the warmest thing in the world — warmer than quilts and blankets, because love is warm.",
        "content": [
            "The quilt is warm, warm.",
            "The blanket is warm, warm.",
            "The little socks are warm too.",
            "Baby cries — boo-hoo.",
            "The quilt cannot hug baby,",
            "the blanket cannot hug baby,",
            "the socks cannot hug baby.",
            "Mommy opens her arms — a hug!",
            "In her arms, gently patted. Boo-hoo fades into little snores. A hug is warmest, because love is warm."
        ],
    },
    {
        "dateStr": "2026-10-15", "kind": "science", "language": "zh",
        "title": "🔬科学故事（0-1岁）：抱抱为什么让人安心",
        "preview": "宝宝一被抱起来，贴着大人的胸口，就慢慢安静了。抱抱里有什么魔法？",
        "moral": "暖暖的皮肤贴着皮肤、听着熟悉的心跳，身体会觉得「很安全」，心跳慢慢变稳，人就放松下来了。",
        "content": [
            "宝宝哭了，抱一抱，",
            "贴着大人暖暖的胸口，",
            "慢慢就安静啦。",
            "抱抱里有魔法吗？",
            "有一个身体的小魔法。",
            "皮肤贴着皮肤，暖暖的。",
            "耳朵听见心跳，咚、咚、咚。",
            "这个声音，宝宝早听惯啦。",
            "身体知道了：很安全。心跳慢慢稳，肌肉慢慢松——抱抱就是这样让宝宝安心的。"
        ],
    },
    {
        "dateStr": "2026-10-15", "kind": "science", "language": "en",
        "title": "🔬 Science Story (0-1 yr): Why Hugs Feel So Safe",
        "preview": "Baby is lifted up, held against a warm chest — and slowly calms down. What magic hides in a hug?",
        "moral": "Warm skin touching skin and a familiar heartbeat tell the body it is safe; the heartbeat steadies and the body relaxes.",
        "content": [
            "Baby cries — a hug comes.",
            "Against a warm, warm chest,",
            "baby slowly calms down.",
            "Is there magic in a hug?",
            "There is a body-magic.",
            "Skin touches skin, warm and close.",
            "Little ears hear a heartbeat —",
            "thump, thump, thump.",
            "A sound baby has always known. The body learns: all is safe. The heartbeat steadies, the muscles soften — that is how a hug comforts baby."
        ],
    },
    # ================= 2026-10-16 =================
    {
        "dateStr": "2026-10-16", "kind": "regular", "language": "zh",
        "title": "晚安，小月亮（0-1岁）",
        "preview": "睡觉前，跟月亮说晚安。小月亮，晚安。小星星，晚安。小猫咪，晚安。宝宝闭上眼，做一个甜甜的梦。",
        "moral": "睡前跟世界一一道晚安，是宝宝的小仪式——安安稳稳，甜甜睡去。",
        "content": [
            "窗帘拉上，灯变暗了。",
            "宝宝睡前说晚安。",
            "小月亮，晚安。",
            "小星星，晚安。",
            "窗台的小猫，晚安。",
            "鱼缸里的小鱼，晚安。",
            "小黄鸭，晚安。",
            "爸爸晚安，妈妈晚安。",
            "宝宝闭上眼睛。整个世界，都轻轻地说：晚安，小宝宝。"
        ],
    },
    {
        "dateStr": "2026-10-16", "kind": "regular", "language": "en",
        "title": "Good Night, Little Moon (0-1 yr)",
        "preview": "Before sleep, baby says good night to the world. Good night, moon. Good night, stars. Good night, kitty. Baby closes eyes for a sweet dream.",
        "moral": "Saying good night to the world is baby's little bedtime ritual — calm, cozy, and off to dreamland.",
        "content": [
            "Curtains drawn, lights turned low.",
            "Baby says good night.",
            "Good night, little moon.",
            "Good night, little stars.",
            "Good night, kitty on the sill.",
            "Good night, little fish.",
            "Good night, rubber duck.",
            "Good night, Daddy. Good night, Mommy.",
            "Baby closes both eyes. The whole world whispers back: good night, little baby."
        ],
    },
    {
        "dateStr": "2026-10-16", "kind": "science", "language": "zh",
        "title": "🔬科学故事（0-1岁）：白天为什么看不见月亮",
        "preview": "月亮晚上挂在天空，白天去哪儿了？其实呀，白天月亮常常也在天上。",
        "moral": "白天月亮多半也在天上，只是太阳光太亮，把淡淡的月光盖住了，所以我们看不清它。",
        "content": [
            "月亮晚上出来，",
            "白天不见了。",
            "月亮睡大觉去了吗？",
            "没有哦。",
            "白天，月亮常常也在天上。",
            "只是太阳太亮啦。",
            "太阳光把天空照得白亮白亮，",
            "淡淡的月光被盖住了。",
            "就像小手电在太阳底下不够亮——月亮还在，只是被太阳的光「抢了风头」。"
        ],
    },
    {
        "dateStr": "2026-10-16", "kind": "science", "language": "en",
        "title": "🔬 Science Story (0-1 yr): Where Is the Moon in the Daytime?",
        "preview": "The moon hangs in the night sky — but where does it go in the daytime? It often stays right up there!",
        "moral": "The moon is often in the sky during the day too; the sun is just so bright that its faint light gets washed out.",
        "content": [
            "The moon comes out at night,",
            "and disappears in the day.",
            "Does it go to sleep?",
            "No, no.",
            "The moon is often up there in daytime.",
            "But the sun is far too bright.",
            "Sunlight whitens the whole sky,",
            "and the moon's faint glow gets covered.",
            "Like a tiny flashlight under the noon sun — the moon is still there, only outshined."
        ],
    },
    # ================= 2026-10-17 =================
    {
        "dateStr": "2026-10-17", "kind": "regular", "language": "zh",
        "title": "小铃铛叮铃铃（0-1岁）",
        "preview": "摇篮上挂着小铃铛。宝宝踢踢腿，叮铃铃。动动小手，叮铃铃。宝宝一动，就有歌声。",
        "moral": "小铃铛告诉宝宝：你的每个小动作，世界都会温柔地回应你。",
        "content": [
            "摇篮边，挂铃铛。",
            "亮晶晶，小小个。",
            "宝宝踢踢腿——叮铃铃。",
            "宝宝动动手——叮铃铃。",
            "打个哈欠——叮，铃。",
            "铃铛爱唱歌，",
            "宝宝爱听歌。",
            "一动一响，一动一响。",
            "小铃铛说：宝宝动一动，世界就回应你。晚安，明天继续唱。"
        ],
    },
    {
        "dateStr": "2026-10-17", "kind": "regular", "language": "en",
        "title": "Ding-a-Ling, Little Bell (0-1 yr)",
        "preview": "A little bell hangs by the crib. Baby kicks — ding-a-ling. Baby waves — ding-a-ling. Every little move makes a little song.",
        "moral": "The little bell tells baby: every small move of yours gets a gentle answer from the world.",
        "content": [
            "By the crib, a little bell.",
            "Shiny, tiny, bright.",
            "Baby kicks — ding-a-ling!",
            "Baby waves — ding-a-ling!",
            "A yawn — ding, a-ling.",
            "The bell loves to sing,",
            "baby loves to listen.",
            "A move, a ring; a move, a ring.",
            "The bell says: every little move of yours, and the world answers. Good night — more songs tomorrow."
        ],
    },
    {
        "dateStr": "2026-10-17", "kind": "science", "language": "zh",
        "title": "🔬科学故事（0-1岁）：铃铛为什么会唱歌",
        "preview": "小铃铛里住着一个小豆豆。宝宝一动，小豆豆跳来跳去——叮铃铃，歌声就来啦。",
        "moral": "铃铛响是因为里面的小铃舌撞击铃壁，金属快速振动发出声音；铃越大越重，声音越低沉。",
        "content": [
            "小铃铛，圆肚皮。",
            "肚子里，住着小豆豆。",
            "铃铛一动，小豆豆跳。",
            "叮——撞一下左边，",
            "铃——撞一下右边。",
            "铃壁被撞得抖呀抖，",
            "抖得又快又欢。",
            "空气跟着抖，钻进耳朵。",
            "叮铃铃——歌声就来啦。大铃铛声音低，小铃铛声音高——每个铃铛都有自己的歌。"
        ],
    },
    {
        "dateStr": "2026-10-17", "kind": "science", "language": "en",
        "title": "🔬 Science Story (0-1 yr): How a Bell Sings",
        "preview": "A tiny pea lives inside the little bell. When the bell moves, the pea hops about — ding-a-ling, and the song begins.",
        "moral": "A bell rings because its little clapper strikes the metal wall, making it quiver fast; bigger bells hum lower, smaller bells ring higher.",
        "content": [
            "The little bell has a round belly.",
            "Inside lives a tiny pea.",
            "The bell moves — the pea hops.",
            "Ding — it hits the left side,",
            "ling — it hits the right side.",
            "The metal wall quivers and quivers,",
            "fast and merry.",
            "The air quivers along, into our ears.",
            "Ding-a-ling — the song arrives! Big bells hum low, small bells ring high — every bell has its own song."
        ],
    },
    # ================= 当当系列 =================
    {
        "dateStr": "2026-10-03", "kind": "dangdang", "episode": 30,
        "title": "当当和小手",
        "preview": "宝宝醒着的时候，小手一挥一挥，像在抓空气。当当趴在摇篮边看——咦？那只小手，朝它的尾巴伸过来啦！",
        "moral": "轻轻的相遇要用轻轻的回应：当当一动不动，把尾巴尖借给了宝宝——这是它送给宝宝的第一个玩具。",
        "content": [
            "下午的阳光，暖暖的。",
            "宝宝醒啦，躺在小床上。",
            "小手一挥，一挥，",
            "小手一抓，一抓，",
            "像在抓空气里的小鱼。",
            "当当趴在摇篮边，看住了。",
            "喵——宝宝真好玩。",
            "忽然，小手伸过来，",
            "朝着当当的尾巴，够呀够。",
            "当当想：动，还是不动？尾巴一摆，宝宝会吓一跳的。",
            "当当选了不动。",
            "它把尾巴尖，轻轻搁在小手边。",
            "小手抓住了！软软的，暖暖的。",
            "宝宝咯咯笑，抓着不撒手。",
            "妈妈轻手轻脚走过来，看见了，笑了：当当，你真好。",
            "当当眯起眼睛。",
            "尾巴尖借给宝宝当玩具，",
            "一动也不动。",
            "这是当当送给宝宝的、轻轻的礼物。"
        ],
    },
    {
        "dateStr": "2026-10-10", "kind": "dangdang", "episode": 31,
        "title": "当当听宝宝咿呀",
        "preview": "宝宝躺在小床上，忽然开口了——啊，咿，哒！没有人教，他自己跟自己说得起劲。当当竖起耳朵：咦，宝宝在跟我说话吗？",
        "moral": "咿咿呀呀是宝宝最早的话；认真的听众，是最好的回应——当当轻轻回了一声「喵」。",
        "content": [
            "早上，太阳照进小床。",
            "宝宝醒着，精神好。",
            "忽然——啊！",
            "咿——呀！",
            "哒——哒！",
            "没有人教，宝宝自己说得起劲。",
            "当当竖起耳朵。",
            "喵？宝宝在叫我吗？",
            "宝宝的小眼睛，转向当当。",
            "咿——呀！",
            "当当轻轻回一声：喵。",
            "咿——呀！喵。",
            "哒——哒！喵。",
            "一个说猫话，一个说宝宝话。",
            "谁也听不懂谁，谁也听得懂谁。",
            "爸爸举着手机，悄悄录下来。",
            "妈妈笑着说：这是你们俩的第一段对话呀。",
            "当当把尾巴卷好，",
            "又轻轻回了一声：喵。"
        ],
    },
    {
        "dateStr": "2026-10-17", "kind": "dangdang", "episode": 32,
        "title": "当当和第一次出门",
        "preview": "秋高气爽，全家要带宝宝第一次下楼晒太阳。小车推起来，当当跟在旁边——世界那么大，当当来护送。",
        "moral": "第一次认识世界，要有耐心的陪伴：走慢一点，看多一点，家的方向永远记得。",
        "content": [
            "周六，天蓝蓝，风轻轻。",
            "爸爸推出小推车。",
            "妈妈把宝宝裹好，",
            "塞进软软的小窝。",
            "第一次出门晒太阳喽。",
            "当当跟在旁边，",
            "不前不后，正好。",
            "楼下，桂花开了，香香的。",
            "大金毛远远看见，",
            "摇着尾巴跑来——",
            "当当回头看摇篮，轻轻「喵」了一声：",
            "小声点，宝宝在睡觉。",
            "大金毛立刻放轻脚步，",
            "围着小车闻了闻，",
            "尾巴摇得慢慢的。",
            "树上的叶子飘下来一片，",
            "转个圈，落在宝宝盖被上。",
            "宝宝在梦里，咧嘴笑了。",
            "回家的时候，夕阳金灿灿。",
            "当当走在最前面，",
            "耳朵一转：家的方向。",
            "世界很大，慢慢认识——",
            "第一次出门，有全家陪着你呢。"
        ],
    },
]
